import 'package:flutter/material.dart';

import 'driver_home_models.dart';

/// Owns static demo data used by the driver home shell.
const driverBottomNavItems = [
  DriverNavItem(icon: Icons.home_rounded, label: 'Home'),
  DriverNavItem(icon: Icons.place_rounded, label: 'Nearby'),
  DriverNavItem(icon: Icons.local_shipping_rounded, label: 'Deliveries'),
  DriverNavItem(icon: Icons.payments_rounded, label: 'Earnings'),
  DriverNavItem(icon: Icons.headset_mic_rounded, label: 'Support'),
];

const initialDriverJobs = [
  DriverJob(
    id: 'drv_job_101',
    title: 'Downtown Pantry Run',
    driverStartLat: 39.7578,
    driverStartLng: -84.1914,
    pickup: 'Target Beavercreek',
    pickupStoreId: 'target_midtown',
    dropoff: 'Northside Deli',
    dropoffLat: 39.7638,
    dropoffLng: -84.1910,
    zone: 'Downtown',
    payEstimateText: r'$24-$31 est.',
    distanceText: '11.4 mi total',
    etaText: '36 min route',
    stage: DeliveryStage.available,
    detailLines: [
      'Pickup window: 11:20 AM - 11:45 AM',
      'Items: 14',
      'Proof required: Photo + timestamp',
    ],
    gradient: [Color(0xFF7FD5CC), Color(0xFFB6E0AE)],
    basePay: 18.5,
    tipAmount: 5.0,
  ),
  DriverJob(
    id: 'drv_job_102',
    title: 'Riverfront Bulk Run',
    driverStartLat: 39.7485,
    driverStartLng: -84.2089,
    pickup: 'Walmart Moraine',
    pickupStoreId: 'walmart_eastgate',
    dropoff: 'Riverfront Print Lab',
    dropoffLat: 39.7582,
    dropoffLng: -84.1769,
    zone: 'Riverfront',
    payEstimateText: r'$28-$36 est.',
    distanceText: '8.1 mi total',
    etaText: '44 min route',
    stage: DeliveryStage.available,
    detailLines: [
      'Pickup window: 11:45 AM - 12:05 PM',
      'Items: 22',
      'Dock entrance required',
    ],
    gradient: [Color(0xFF8FC9F2), Color(0xFFADE6D2)],
    basePay: 22.0,
    tipAmount: 7.0,
  ),
  DriverJob(
    id: 'drv_job_103',
    title: 'North Corridor Office Refill',
    driverStartLat: 39.8040,
    driverStartLng: -84.1790,
    pickup: 'Target Huber Heights',
    pickupStoreId: 'target_harbor',
    dropoff: 'Vandalia Coffee House',
    dropoffLat: 39.8904,
    dropoffLng: -84.1988,
    zone: 'North Corridor',
    payEstimateText: r'$20-$26 est.',
    distanceText: '7.3 mi total',
    etaText: '31 min route',
    stage: DeliveryStage.available,
    detailLines: [
      'Pickup window: 12:05 PM - 12:25 PM',
      'Items: 10',
      'Hand-off requires signature',
    ],
    gradient: [Color(0xFF9FD3E2), Color(0xFFC8E8C5)],
    basePay: 16.0,
    tipAmount: 4.5,
  ),
  DriverJob(
    id: 'drv_job_104',
    title: 'Oakwood Catering Assist',
    driverStartLat: 39.7395,
    driverStartLng: -84.1810,
    pickup: 'Target Beavercreek',
    pickupStoreId: 'target_midtown',
    dropoff: 'Oakwood Bakery',
    dropoffLat: 39.7253,
    dropoffLng: -84.1746,
    zone: 'South Dayton',
    payEstimateText: r'$18-$24 est.',
    distanceText: '6.2 mi total',
    etaText: '28 min route',
    stage: DeliveryStage.available,
    detailLines: [
      'Pickup window: 12:10 PM - 12:30 PM',
      'Items: 8',
      'Customer note: Ring rear entrance bell',
    ],
    gradient: [Color(0xFFBFD7EE), Color(0xFFDAEBC0)],
    basePay: 14.9,
    tipAmount: 3.75,
  ),
  DriverJob(
    id: 'drv_job_220',
    title: 'Midday Campus Express',
    driverStartLat: 39.7610,
    driverStartLng: -84.1876,
    pickup: 'Target Huber Heights',
    pickupStoreId: 'target_harbor',
    dropoff: 'Elm Street Cafe',
    dropoffLat: 39.7469,
    dropoffLng: -84.1824,
    zone: 'University District',
    payEstimateText: r'$19-$25 est.',
    distanceText: '8.7 mi total',
    etaText: '34 min route',
    stage: DeliveryStage.assigned,
    detailLines: [
      'Status: Assigned and ready for pickup',
      'Items: 9',
      'Customer note: Call upon arrival',
    ],
    gradient: [Color(0xFFC2DCAA), Color(0xFFE6E6BA)],
    basePay: 15.75,
    tipAmount: 4.0,
  ),
  DriverJob(
    id: 'drv_job_221',
    title: 'Kettering Clinic Restock',
    driverStartLat: 39.7340,
    driverStartLng: -84.2174,
    pickup: 'Walmart Moraine',
    pickupStoreId: 'walmart_eastgate',
    dropoff: 'Kettering Med Supply',
    dropoffLat: 39.6892,
    dropoffLng: -84.1713,
    zone: 'Kettering',
    payEstimateText: r'$23-$30 est.',
    distanceText: '7.8 mi total',
    etaText: '33 min route',
    stage: DeliveryStage.assigned,
    detailLines: [
      'Status: Assigned and ready for pickup',
      'Items: 15',
      'Loading zone: South receiving dock',
    ],
    gradient: [Color(0xFFA6D3DA), Color(0xFFD6E9C2)],
    basePay: 17.1,
    tipAmount: 5.2,
  ),
  DriverJob(
    id: 'drv_job_330',
    title: 'Warehouse Final Leg',
    driverStartLat: 39.7104,
    driverStartLng: -84.1970,
    pickup: 'Walmart Moraine',
    pickupStoreId: 'walmart_eastgate',
    dropoff: 'Riverbend Office Co.',
    dropoffLat: 39.7521,
    dropoffLng: -84.2033,
    zone: 'West Dayton',
    payEstimateText: r'$16-$22 est.',
    distanceText: '5.1 mi total',
    etaText: '24 min route',
    stage: DeliveryStage.outForDelivery,
    detailLines: [
      'Status: Out for delivery',
      'Items: 7',
      'Proof mode: Contactless photo',
    ],
    gradient: [Color(0xFF95D0D8), Color(0xFFD0E8C5)],
    basePay: 14.25,
    tipAmount: 3.5,
  ),
  DriverJob(
    id: 'drv_job_331',
    title: 'Wright Tech Priority Drop',
    driverStartLat: 39.7802,
    driverStartLng: -84.1304,
    pickup: 'Target Beavercreek',
    pickupStoreId: 'target_midtown',
    dropoff: 'Wright Tech Hub',
    dropoffLat: 39.7815,
    dropoffLng: -84.0582,
    zone: 'East Dayton',
    payEstimateText: r'$22-$29 est.',
    distanceText: '4.8 mi total',
    etaText: '20 min route',
    stage: DeliveryStage.outForDelivery,
    detailLines: [
      'Status: Out for delivery',
      'Items: 6',
      'Security desk check-in required',
    ],
    gradient: [Color(0xFF9ACED4), Color(0xFFD3E8C8)],
    basePay: 16.6,
    tipAmount: 4.8,
  ),
  DriverJob(
    id: 'drv_job_410',
    title: 'Morning Produce Drop',
    driverStartLat: 39.7597,
    driverStartLng: -84.1890,
    pickup: 'Target Beavercreek',
    pickupStoreId: 'target_midtown',
    dropoff: 'Central Kitchen Co-op',
    dropoffLat: 39.7609,
    dropoffLng: -84.1752,
    zone: 'Downtown',
    payEstimateText: r'$21-$27 est.',
    distanceText: '9.9 mi total',
    etaText: '39 min route',
    stage: DeliveryStage.delivered,
    detailLines: [
      'Completed at 9:42 AM',
      'Items: 12',
      'Proof uploaded successfully',
    ],
    gradient: [Color(0xFFA8D6D9), Color(0xFFDBE8BE)],
    basePay: 17.25,
    tipAmount: 6.0,
  ),
];

const initialDriverSupportCases = [
  DriverSupportCase(
    id: 'DS-219',
    title: 'Pickup readiness mismatch',
    status: 'In review',
    summary: 'Store marked ready but pallet was still being staged.',
    linkedDeliveryId: 'drv_job_220',
  ),
  DriverSupportCase(
    id: 'DS-224',
    title: 'Drop-off gate access issue',
    status: 'Open',
    summary: 'Customer access instructions were incomplete for Dayton site.',
    linkedDeliveryId: 'drv_job_330',
  ),
];
