set shell := ["bash", "-cu"]

# List available recipes
default:
    @just --list

# Run tests
test:
    @echo "No tests have been developed yet."

# Analyze code
check:
    npm run check

# Format code
format:
    npm run format

# Install dependencies
deps:
    # Use install over clean-install to ensure package-lock.json can be updated.
    # This recipe will only ever be run in a development context.
    npm i --no-fund

# Clean build artifacts
clean:
    sudo rm -rf .next

# Build production artifact
build:
    npm run build
