import js from '@eslint/js';
import globals from 'globals';

export default [
  {
    // Built artifacts are regenerated by `npm run build`, so lint the sources instead.
    ignores: ['dist/**'],
  },
  js.configs.recommended,
  {
    files: ['src/**/*.js'],
    languageOptions: {
      globals: {
        ...globals.node,
      },
      sourceType: 'module',
    },
  },
  {
    files: ['**/*.cjs'],
    languageOptions: {
      globals: {
        ...globals.jest,
        ...globals.node,
      },
      sourceType: 'commonjs',
    },
  },
];
