name: main test

on:
  pull_request:
    paths:
      - apps/main/**
      - apps/shared/**
      - .github/workflows/main.test.yml
  push:
    paths:
      - apps/main/**
      - apps/shared/**
      - .github/workflows/main.test.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/main
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter test
