name: test:mocks

on:
  pull_request:
    paths:
      - mocks/**
      - .github/workflows/mocks.test.yml
  push:
    paths:
      - mocks/**
      - .github/workflows/mocks.test.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mocks
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: mocks/package-lock.json
      - run: npm ci
      - run: npm test
